#!/usr/bin/python3

# Generate vectors.S, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

def pushErrCode(trapno):
    if i in [8, 10, 11, 12, 13, 14, 17]:
        # these traps have a hardware pushed error code
        return ""
    else:
        return "push $0"

# TOP
print("""
# generated by vectors.py - do not edit
# handlers""")

# VECTOR CODES
print(".globl alltraps")
for i in range(256):
    print(f"""
.globl vector{i}
vector{i}:
  {pushErrCode(i)}
  push ${i}
  jmp alltraps""")

# VECTOR ARRAY
print("""
# vector table
.data
.globl vectors
vectors:""")
for i in range(256):
    print(f"  .quad vector{i}")
